intervall
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly # daily
    open-pull-requests-limit: 20

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly # daily
    open-pull-requests-limit: 20
