version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1000
    assignees:
      - "attajak"
    labels:
      - "dependencies"
      - "javascript"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1000
    assignees:
      - "attajak"
    labels:
      - "dependencies"
      - "github-actions"
